version: '3'

services:
  # ChromaDB Vector Database
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.4.22
    restart: always
    ports:
      - "8000:8000"  # Expose ChromaDB port
    volumes:
      - ./chroma_data:/chroma/chroma  # Persist ChromaDB data

  # RAG Service API
  rag-service:
    build:
      context: ../..  # Build from the root directory
      dockerfile: ./rag/deployment/Dockerfile
    restart: always
    ports:
      - "8090:8090"  # Expose RAG service port
    depends_on:
      - chromadb
    environment:
      - CHROMA_HOST=chromadb  # Use service name for Docker networking
      - CHROMA_PORT=8000
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8090
      - ENABLE_AUTH=false  # Disable auth for easier testing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  chroma-data:
    driver: local